apiVersion: batch/v1
kind: Job
metadata:
  generateName: tarek-gpu-ssd-job-
  labels:
      type: tarek_ssd_model_exploration
spec:
  template:
    metadata:
      name: sweep-gpu
      labels:
        type: andys_ssd_model_exploration
    spec:
      restartPolicy: Never # OnFailure
      imagePullPolicy: Always
      priorityClassName: default
      containers:
      - name: gpu-container
        image: nervana-dockrepo01.fm.intel.com:5001/tarek_ssd_model_exploration:test_01
        # command: ['sleep','infinity'] # for debugging (`kubectl create -f gpu_job.yaml` then `kubectl exec -it <pod name> -- bash`)
        securityContext: 
          runAsUser: 11826255 # tareknas id (try running `id`)
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 2 GPUs
        volumeMounts:
        # - mountPath: /usr/local/nvidia
        #   name: local-nvidia
        - mountPath: "/mnt"
          name: nfs
        - mountPath: "/dataset"
          name: dataset
        env:
        - name: http_proxy
          value: http://proxy-chain.intel.com:911
        - name: https_proxy
          value: http://proxy-chain.intel.com:912
        - name: HTTP_PROXY
          value: http://proxy-chain.intel.com:911
        - name: HTTPS_PROXY
          value: http://proxy-chain.intel.com:912
        - name: no_proxy
          value: localhost,127.0.0.1,intel.com,.intel.com,cluster,.cluster,10.0.0.0/8,172.168.0.0/16,192.168.0.0/16,10.54.8.248,10.54.4.19,10.54.8.18,132.233.52.91,localhost,127.0.0.1,intel.com,.intel.com,cluster,.cluster,10.54.8.137,10.54.8.241,10.54.8.246,10.54.8.247,10.54.8.248,10.54.4.19,10.105.186.109,172.17.0.1,10.105.186.110,172.17.0.1,10.105.186.111,10.105.186.112,172.17.0.1,10.105.186.113,172.17.0.1,10.105.186.114,10.105.186.115,192.168.1.246,10.105.186.116,172.17.0.1,10.105.186.117,172.17.0.1,10.105.186.118,172.17.0.1,10.105.186.119,10.105.186.120,10.105.186.121,10.105.186.122
        - name: NO_PROXY
          value: localhost,127.0.0.1,intel.com,.intel.com,cluster,.cluster,10.0.0.0/8,172.168.0.0/16,192.168.0.0/16,10.54.8.248,10.54.4.19,10.54.8.18,132.233.52.91,localhost,127.0.0.1,intel.com,.intel.com,cluster,.cluster,10.54.8.137,10.54.8.241,10.54.8.246,10.54.8.247,10.54.8.248,10.54.4.19,10.105.186.109,172.17.0.1,10.105.186.110,172.17.0.1,10.105.186.111,10.105.186.112,172.17.0.1,10.105.186.113,172.17.0.1,10.105.186.114,10.105.186.115,192.168.1.246,10.105.186.116,172.17.0.1,10.105.186.117,172.17.0.1,10.105.186.118,172.17.0.1,10.105.186.119,10.105.186.120,10.105.186.121,10.105.186.122
      # nodeSelector:
      #     fastweights: "true"
      volumes:
      - nfs:
          server: fmcfs05n02b-03.fm.intel.com
          path: "/nrv_algo_home01/tareknas" # Unfortunately this has to be a specific home directory (and not all home directories)
        name: nfs
